apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURZdwpNVEEyTURkYUZ3MDBNakE0TURZd01UQTJNRGRhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZHRLTHRlSm1CV0t3T2lqdUZtLzBvR3BiWjVVeDlkb29NZXZlWktSc0M4c0VZa2FYWQpCSDE0Z095bXdtcUlwSm0vdDFTaWRmYnlnajBnTWczSGVzamtsV282aEhoS2NuSERsZXlaM2dJa1FyZG5DT0xpCmdNUzdJc3ErRW5PS0NQTXg1ODBBcFA3NU1zaFUzTElSOTZqcks4a1hpdXAxRHRsR0FQeWZWYmZyVExVR3NQMTIKZmJHcFNXT2ZKbWdidCtnanY5aGlFdlFaVERrMTdXN1NNdjgwQVlKK0Uvejl1YjMxZ3YzUzRIWUlRbkZrNkdiVwpranhiTGVhTDFQQWlhRjFFb21KTDZhaXFoRUZhNnFwYU5SVzlqb1NmNlhrN1hwTW00QVZJVnkzNmFHY1Y2NkdqCmdEZ2VoNmE0bkRUZWVnVjkvVjRVM3ZtUGIxcmZaK3hLRUprVEFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlRzam9WeVZ3c3ZkTUw0ME9rVwpLamtQdzBQMkF6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFFOCs0SUxZTGR3TVI1ekJLRVBaWTVYbmx5S0tMCnFsaWJtamtXRGZnVmlsUTg3alN1N1VpTS95d1FMekFDWXBoS0JPVUdGYmxpWm1ldHFPRU1WbnFsQXE3NzdReWgKQkRwUEZyWmJjV3pUSDhTbC8vQXpXejh1Q3oyQzVENnNWOVlzZTVrVW5zcWpaN292WEpYNDNNZys5SGhMVHdCUQpXbkh2YzJPNDRyeG5Gcld4WEhXTjNkQkhJdmRwdHlTWjgrQWhlak1ZLzNwTVBLZ3JyS0lsVjlwRnNxWGR3UmR4CjlnZFc5VVY1Snp2V3p6eHhYT1FqYTV1MFp4MHZPekI5Qlc5R0RSRzM4UEtweUNpVVNBWEN1OFBXY0U1YWptT2wKcnFKUTN0aUZBcjJtbmxpbTJKNndKYnh3TXFWZjN6VklCcEp2MWNsTG5jczhFdmY5Y2FYK0pWdEVzUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://84fa9d4e-f4c2-47ae-a340-9dfc5e6b8e45.k8s.ondigitalocean.com
  name: do-nyc1-k8s-iniciativa
contexts:
- context:
    cluster: do-nyc1-k8s-iniciativa
    user: do-nyc1-k8s-iniciativa-admin
  name: do-nyc1-k8s-iniciativa
current-context: do-nyc1-k8s-iniciativa
users:
- name: do-nyc1-k8s-iniciativa-admin
  user:
    token: dop_v1_ea5d93ca8e9c6f7b3d41969ac33273dfa26ddab5040ca3c159027feaeed7a0fd
